name: chatify
description: Chat package for flutter
version: 0.1.4
homepage: https://github.com/karrarfalih/chatify

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  diffutil_dart: ^4.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.13
  get: ^4.7.2
  http: ^1.5.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  lottie: ^3.3.1
  meta: ^1.16.0
  rxdart: ^0.28.0
  swipeable_tile: ^2.0.1
  universal_html: ^2.2.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/