const chatifyAr = {
  "Messeges": "الرسائل",
  "Message": "رسالة",
  "Search": "بحث",
  "Delete": "حذف",
  "Copy": "نسخ",
  "Edit": "تعديل",
  "Reply": "رد",
  "Confirm": "تأكيد",
  "Cancel": "إلغاء",
  "Ok": "موافق",
  "Yes": "نعم",
  "No": "لا",
  "Are you sure you want to delete the message?":
      "هل أنت متأكد من حذف الرسالة؟",
  "Are you sure you want to delete these messages?":
      "هل أنت متأكد من حذف الرسائل؟",
  "Delete %s messages?": "حذف %s رسالة",
  "Selected": "محددة",
  "Delete for all": "حذف للجميع",
  "Are you sure you want to delete the chat?":
      "هل أنت متأكد من حذف المحادثة؟",
  "Delete chat": "حذف المحادثة",
  "Select media": "اختر ملف",
  "Add caption": "إضافة تعليق",
  "Selected media": "الملفات المختارة",
  "Waiting for connection...": "في انتظار الاتصال...",
  "Connecting...": "جاري الاتصال...",
  "Online": "متصل",
  "Last seen recently": "آخر ظهور قبل قليل",
  "Last seen just now": "آخر ظهور قبل ثوانٍ",
  "Last seen %s minutes ago": "آخر ظهور منذ %s دقيقة",
  "Last seen %s hours ago": "آخر ظهور منذ %s ساعة",
  "Last seen %s days ago": "آخر ظهور منذ %s يوم",
  "Last seen %s weeks ago": "آخر ظهور منذ %s أسبوع",
  "Last seen a long time ago": "آخر ظهور منذ وقت طويل",
  "Me": "أنا",
  "Save": "حفظ",
  "Saved to gallery": "تم حفظها في المعرض",
  "Failed to save": "فشل في الحفظ",
  "No messages": "لا توجد رسائل",
  "Saved messages": "الرسائل المحفوظة",
  "Support": "الدعم والمساعدة",
  "New message": "رسالة جديدة",
  "deletedMessage": "رسالة محذوفة",
  "Edited": "تم التعديل",
  "Say hi!": "قل مرحبا!",
  "No recent emojis": "لا توجد رموز تعبيرية مستخدمة مؤخرًا",
  "Member": "شخص",
  "Slide to cancel": "اسحب للإلغاء",
  "To: ": "إلى: ",
  "Image message": "صورة",
  "Voice message": "رسالة صوتية",
  "Unsupported message": "رسالة غير مدعومة",
  "Deleted account": "حساب محذوف",
  "Typing": "يكتب الآن",
  "Recording": "يسجل",
  "Sending media": "جاري الإرسال",
  "Please grant permission to access your photos":
      "يرجى الموافقة على الإذن للوصول إلى صورك",
};
