const chatifyEn = {
  "Messeges": "Messages",
  "Message": "Message",
  "Search": "Search",
  "Delete": "Delete",
  "Copy": "Copy",
  "Edit": "Edit",
  "Reply": "Reply",
  "Confirm": "Confirm",
  "Cancel": "Cancel",
  "Ok": "Ok",
  "Yes": "Yes",
  "No": "No",
  "Are you sure you want to delete the message?":
      "Are you sure you want to delete the message?",
  "Are you sure you want to delete these messages?":
      "Are you sure you want to delete these messages?",
  "Delete %s messages?": "Delete %s messages?",
  "Selected": "Selected",
  "Delete for all": "Delete for all",
  "Are you sure you want to delete the chat?":
      "Are you sure you want to delete the chat?",
  "Delete chat": "Delete chat",
  "Select media": "Select media",
  "Add caption": "Add caption",
  "Selected media": "Selected media",
  "Waiting for connection...": "Waiting for connection...",
  "Connecting...": "Connecting...",
  "Online": "Online",
  "Last seen recently": "Last seen recently",
  "Last seen just now": "Last seen just now",
  "Last seen %s minutes ago": "Last seen %s minutes ago",
  "Last seen %s hours ago": "Last seen %s hours ago",
  "Last seen %s days ago": "Last seen %s days ago",
  "Last seen %s weeks ago": "Last seen %s weeks ago",
  "Last seen a long time ago": "Last seen a long time ago",
  "Me": "Me",
  "Save": "Save",
  "Saved to gallery": "Saved to gallery",
  "Failed to save": "Failed to save",
  "No messages": "No messages",
  "Saved messages": "Saved messages",
  "Support": "Support",
  "New message": "New message",
  "Deleted message": "Deleted message",
  "Edited": "Edited",
  "Say hi!": "Say hi!",
  "No recent emojis": "No recent emojis",
  "Member": "Member",
  "Slide to cancel": "Slide to cancel",
  "To: ": "To: ",
  "Image message": "Image message",
  "Voice message": "Voice message",
  "Unsupported message": "Unsupported message",
  "Deleted account": "Deleted account",
  "Typing": "Typing",
  "Recording": "Recording",
  "Sending media": "Sending media",
  "Please grant permission to access your photos":
      "Please grant permission to access your photos",
};
