name: chatify_uploader_firebase_storage
description: "Chatify's firebase storage implementation for uploading files and messages."
version: 0.0.2
homepage: https://github.com/karrarfalih/chatify

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chatify: ^0.1.6
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
