name: chatify_reply
description: "A new Flutter package project."
version: 0.0.2
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chatify: ^0.1.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get: ^4.7.2
  iconsax: ^0.0.8
  swipeable_tile: ^2.0.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
