name: chatify_voice_message
description: "Chatify's voice message implementation."
version: 0.0.1
homepage: https://github.com/karrarfalih/chatify

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chatify: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
