name: chatify_image_message
description: "Chatify's image message implementation."
version: 0.0.3
homepage: https://github.com/karrarfalih/chatify

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chatify: ^0.1.6
  iconsax: ^0.0.8
  uuid: ^4.5.1
  flutter_image_compress: ^2.4.0
  image_picker: ^1.2.0
  blur: ^4.0.2
  zoom_widget: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
