name: chatify_text_message
description: "Chatify's text message implementation."
version: 0.0.1
homepage: https://github.com/karrarfalih/chatify

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chatify: ^0.1.3
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
